# *TODO: 0 ( 1/1 )
# TODO 2: MAKE A RANDOM NUMBER GENERATOR THAT WILL CORRESPOND WITH THE NUMBER OF CHOICES
# TODO 3: make the computer make a choice
# TODO 4: MAKE THE USER MAKE A CHOICE
# TODO 5: MAKE A FUNCTION THAT DISCREMANATE THE WINNER
# TODO 6 : MAKE THE PLAYER HAS 3 LIVES
# TODO 7 : TRACK THE NUMBER OF WINS, WHOEVER GOT 3 CORRECT WINS WOULD BE WINNER AND THE GAME ENDS


choices = ['rock', 'paper', 'scissors']



